### ISSUE TITLE
dev status

### ISSUE THREAD

**Issue by gitrj95** [joaotavora/beardbolt#1]
is this still being developed? are there plans to place on melpa or elpa?

**Comment by joaotavora** [comment]
It's not abandoned, but I haven't got any major changes planned, unless people start asking for them. 

As to place it in melpa/elpa, I don't mind that.  ELPA is going to be tricky, because this is a fork of RMSbolt and I'm not sure all the contributors before I forked have FSF copyright assignments.  But Non-GNU ELPA is probably fine.

The only thing is I don't have a lot of time to dedicate to this.  Maybe you can help.  I'm pinging @monnier here since he is the Non-GNU ELPA person of contact.

**Comment by monnier** [comment]
> It's not abandoned, but I haven't got any major changes planned, unless
> people start asking for them. 
>
> As to place it in melpa/elpa, I don't mind that.  ELPA is going to be
> tricky, because this is a fork of RMSbolt and I'm not sure all the
> contributors before I forked have FSF copyright assignments.  But Non-GNU
> ELPA is probably fine.

I just looked at the code and you removed/rewrote pretty much all the
code written by those who don't have a copyright assignment (most of
them added support for other languages).

There are a few lines left from Erik Arvstedt, but it's definitely small
enough to fall within the copyright-exempt category.

So, it's definitely a candidate for GNU ELPA.  If you're interested, let
me know and then please change the copyright lines accordingly (oh and
please fix this "the end is not the end" thingy, as seen in patch
below).


        Stefan


diff --git a/beardbolt.el b/beardbolt.el
index b534542..7d12f9a 100644
--- a/beardbolt.el
+++ b/beardbolt.el
@@ -51,7 +51,7 @@
   :type 'string :safe (lambda (v) (or (listp v) (stringp v))))
 (bb--defoption bb-disassemble nil
   "Non-nil to assemble then disassemble an output binary."
-  :type 'boolean :safe 'booleanp)
+  :type 'boolean :safe #'booleanp)
 (bb--defoption bb-asm-format 'att
   "Which output assembly format to use.
 Passed directly to compiler or disassembler."
@@ -551,6 +551,8 @@ Argument STR compilation finish status."
     (with-current-buffer asm-buffer
       (bb--asm-mode)
       (setq bb--source-buffer src-buffer)
+      ;; FIXME: Do we really need to bind the `inhibit-*' vars around
+      ;; the calls to `display-buffer' as well?
       (let* ((inhibit-modification-hooks t)
              (inhibit-read-only t)
              (window
@@ -783,9 +785,9 @@ With prefix argument, choose from starter files in `bb-starter-files'."
   (buffer-disable-undo)
   (local-set-key (kbd "q") 'quit-window))
 
-(provide 'beardbolt)
-
-;;; beardbolt.el ends here
 ;; Local Variables:
 ;; read-symbol-shorthands: (("bb-" . "beardbolt-"))
 ;; End:
+
+(provide 'beardbolt)
+;;; beardbolt.el ends here

**Comment by gitrj95** [comment]
i don't have a use case to extend this (principally interested in the languages you already support), but i would love this to go onto elpa - either gnu or non gnu. what features did you have in mind for this?

**Comment by joaotavora** [comment]
I'd mostly appreciate if you could give it some hard testing.  I'm not using at the moment.

Once in a while I remember noticing a window-configuration bug, which was very annoying.  See if you can trigger it and try to come up with a reprodution recipe.  I can start the elpa process, since Stefan says it's OK.

**Comment by gitrj95** [comment]
Regrettably don't have the time!  Will come back to this later.
